# Configure main menu and social menu

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[main.params]
icon = "home"

[[main]]
identifier = "glossary"
name = "Glossary"
url = "/glossary/"
weight = 22

[main.params]
icon = "book"

[[main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[main.params]
icon = "article"

[[main]]
identifier = "newsletter"
name = "Newsletter"
url = "/newsletter/"
weight = 25

[main.params]
icon = "news"

[[main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 30

[main.params]
icon = "mail"

[[main]]
identifier = "twitter"
name = "@motorstatsio"
url = "https://x.com/motorstatsio"
weight = 40

[main.params]
icon = "brand-twitter"
newtab = true