baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "motorStats.io"
theme = ["github.com/CaiJimmy/hugo-theme-stack/v3"]

pagination.pagerSize = 10

[params]
  mainSections = ["posts"]
  featuredImageField = "image"

  [params.sidebar]
    compact = false

    subtitle = "Analytics, data, and race insights for IndyCar"

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/logo.png"
	

  [params.article]
    math = false
    toc = true
    readingTime = true
	
  [params.home]
    showSummary = true

  [params.footer]
    since = 2025
    customText = "Motorsports analytics for curious fans"

[taxonomies]
  category = "categories"
  tag = "tags"
